import type { Destination } from "./types";

/**
 * As sete escalas da QIMO Croatia Experience 2026.
 * Conteúdo integral do guia QIMO (introduções, pontos turísticos, info prática).
 * Rota oficial (programa): Marina Baotić ⇄ Dubrovnik, com swim stops.
 */
export const destinations: Destination[] = [
  {
    slug: "trogir",
    day: 1,
    date: "2026-07-25",
    name: "Trogir",
    tagline: "A cidade-museu de pedra — Patrimônio da UNESCO",
    route: "Embarque · Marina Baotić",
    coordinates: { lat: 43.5169, lng: 16.2517 },
    tempC: 29,
    sunset: "20:28",
    hero: { src: "/images/hero-trogir.svg", alt: "As muralhas cor de mel de Trogir ao entardecer" },
    introduction: [
      "Uma das cidades medievais mais bem preservadas da Europa e Patrimônio da UNESCO desde 1997 — tida como o complexo românico-gótico mais íntegro da Europa Central.",
      "Fundada por gregos no séc. III a.C., condensa camadas romanas, venezianas e barrocas em ruelas de dez minutos de caminhada. A atmosfera é mais lenta que a de Split ou Dubrovnik — o primeiro contato perfeito com a Dalmácia. É daqui, da Marina Baotić, que a QIMO solta as amarras.",
    ],
    pointsOfInterest: [
      { name: "Catedral de São Lourenço", description: "Katedrala Sv. Lovre (1213); o Portal de Radovan (1240) é o mais importante portal medieval da região. Campanário de 47 m. ~45–60 min · €7–10." },
      { name: "Fortaleza Kamerlengo", description: "Tvrđava Kamerlengo — fortaleza veneziana do séc. XV na orla, hoje palco de cinema ao ar livre. Bela vista ao pôr do sol." },
      { name: "Palácio Cipiko", description: "Cipikova palača — edifício gótico do séc. XV em frente à catedral, com janelas entalhadas notáveis." },
      { name: "Loggia & São Sebastião", description: "A Loggia da cidade e a Capela de São Sebastião (1476), com a torre do relógio renascentista, na praça principal." },
      { name: "Portão Norte & Kula sv. Marka", description: "O Portão Norte com a estátua de São João de Trogir (padroeiro) e a torre cilíndrica de São Marcos (séc. XV)." },
      { name: "Riva & Ilha de Čiovo", description: "Orla de palmeiras e iates; a ponte para Čiovo dá a foto da “cidade flutuante”. Praias e a Laguna Azul a um curto trajeto de barco." },
    ],
    restaurantIds: ["konoba-trs", "don-dino", "mare-ciovo", "dionis", "kamerlengo-rest", "olive-trogir"],
    gallery: [
      { src: "/images/trogir-1.svg", alt: "Vielas de pedra de Trogir" },
      { src: "/images/trogir-2.svg", alt: "Orla de Trogir ao amanhecer" },
      { src: "/images/hero-trogir.svg", alt: "Trogir vista do canal" },
    ],
    practical: [
      { label: "Embarque", value: "A partir das 14h · porto de Trogir" },
      { label: "Endereço", value: "Obala bana Berislavića 17" },
      { label: "Guarda-volumes", value: "Castelo Kamerlengo · €5/mala" },
      { label: "Moeda", value: "Euro (€)" },
    ],
  },
  {
    slug: "hvar",
    day: 2,
    date: "2026-07-26",
    name: "Hvar",
    tagline: "A ilha do sol, da lavanda e do glamour",
    route: "Marina Baotić → Hvar",
    coordinates: { lat: 43.1729, lng: 16.4411 },
    tempC: 30,
    sunset: "20:26",
    hero: { src: "/images/hero-hvar.svg", alt: "Hvar e o arquipélago de Pakleni ao pôr do sol" },
    introduction: [
      "A ilha mais ensolarada da Europa (média citada de 2.726 horas de sol/ano) e o destino mais badalado da Croácia. Cidade veneziana de pedra branca, com a Riva mais luxuosa do país.",
      "Mas há muito além da festa: oito séculos de arquitetura, o primeiro teatro público da Europa (1612) e as deslumbrantes ilhas Pakleni, a minutos de táxi-barco.",
    ],
    pointsOfInterest: [
      { name: "Fortaleza Fortica (Španjola)", description: "Sobre sítio ilírio; vista magnífica de Hvar Town e das Pakleni. Subida 20–30 min (ou táxi), café no terraço. Deslumbrante ao pôr do sol." },
      { name: "Praça de São Estêvão", description: "Trg Sv. Stjepana — a maior praça antiga da Dalmácia (4.500 m²) e o coração social da cidade." },
      { name: "Arsenal & Teatro (1612)", description: "Considerado o primeiro teatro público da Europa, aberto a todas as classes — um marco civilizatório." },
      { name: "Mosteiro Franciscano", description: "Franjevački samostan, à beira-mar, com cipreste antigo e o célebre quadro da Última Ceia." },
      { name: "Ilhas Pakleni", description: "Paraíso de enseadas cristalinas a minutos de táxi-barco: Palmižana (jardim botânico), Jerolim, Marinkovac e Sveti Klement." },
      { name: "Campos de lavanda & Stari Grad", description: "No interior (Velo Grablje, Brusje) e a vila histórica de Stari Grad, cuja planície agrícola é Patrimônio UNESCO." },
    ],
    restaurantIds: ["gariful", "mediterraneo", "zori", "laganini", "san-marco", "dalmatino"],
    gallery: [
      { src: "/images/hvar-1.svg", alt: "Águas turquesa de Pakleni" },
      { src: "/images/hvar-2.svg", alt: "Telhados de Hvar" },
      { src: "/images/hero-hvar.svg", alt: "Hvar ao entardecer" },
      { src: "/images/hvar-swim.svg", alt: "Águas turquesa das ilhas Pakleni" },
    ],
    practical: [
      { label: "Fundeio", value: "Baía de Hvar / Pakleni" },
      { label: "Não perca", value: "Pôr do sol da Fortica" },
      { label: "Swim stop", value: "Pakleni — águas cristalinas" },
      { label: "Moeda", value: "Euro (€)" },
    ],
  },
  {
    slug: "korcula",
    day: 3,
    date: "2026-07-27",
    name: "Korčula",
    tagline: "A “pequena Dubrovnik”, terra de Marco Polo",
    route: "Hvar → Korčula",
    coordinates: { lat: 42.9606, lng: 17.1358 },
    tempC: 29,
    sunset: "20:22",
    hero: { src: "/images/hero-korcula.svg", alt: "A cidade fortificada de Korčula avançando sobre o mar" },
    introduction: [
      "Cidade fortificada medieval em traçado de espinha de peixe (para circular a brisa e bloquear os ventos), com muralhas do séc. XIII e telhados de terracota — a “pequena Dubrovnik”.",
      "Forte tradição naval e de cantaria, vinhos brancos autóctones e a grande lenda: a cidade reivindica ser a terra natal de Marco Polo (1254–1324).",
    ],
    pointsOfInterest: [
      { name: "Catedral de São Marcos", description: "Katedrala Sv. Marka (séc. XV–XVI), com retábulo de Tintoretto. Suba o campanário (escada estreita com semáforo!) para a vista da cidade." },
      { name: "Casa de Marco Polo", description: "Kuća Marka Pola — suposta casa natal do explorador; centro interpretativo e torre com vista panorâmica. ~1–2 h." },
      { name: "Veliki Revelin", description: "Torre defensiva do séc. XV no portão sul, com exposição permanente da Moreška e vista da entrada da cidade." },
      { name: "Muralhas (Gradske zidine)", description: "As muralhas do séc. XIII estão entre as mais preservadas da Croácia, com vistas impressionantes do mar." },
      { name: "Moreška", description: "A dança das espadas: drama dançado de 400 anos, às 21h no cinema de verão. Performance festiva em 29/jul (São Teodoro)." },
      { name: "Šetalište Petra Kanavelića", description: "A orla à beira das muralhas, perfeita para caminhar ao pôr do sol, com a península de Pelješac ao fundo." },
    ],
    restaurantIds: ["ld-restaurant", "filippi", "konoba-mate", "adio-mare", "lole", "aterina"],
    gallery: [
      { src: "/images/korcula-1.svg", alt: "Ruas em espinha de peixe de Korčula" },
      { src: "/images/korcula-2.svg", alt: "Muralhas de Korčula ao mar" },
      { src: "/images/hero-korcula.svg", alt: "Korčula vista do canal" },
      { src: "/images/korcula-swim.svg", alt: "Águas turquesa de Korčula" },
    ],
    practical: [
      { label: "Fundeio", value: "Frente à cidade velha" },
      { label: "Vinho local", value: "Pošip · Grk (Lumbarda)" },
      { label: "Não perca", value: "Moreška · catedral" },
      { label: "Moeda", value: "Euro (€)" },
    ],
  },
  {
    slug: "dubrovnik",
    day: 4,
    date: "2026-07-28",
    name: "Dubrovnik",
    tagline: "A Pérola do Adriático",
    route: "Korčula → Dubrovnik",
    coordinates: { lat: 42.6407, lng: 18.1077 },
    tempC: 28,
    sunset: "20:17",
    hero: {
      src: "/images/hero-dubrovnik.svg",
      alt: "As muralhas de Dubrovnik abraçando a cidade velha sobre o Adriático",
    },
    introduction: [
      "Há cidades que se visitam e cidades que se contemplam. Dubrovnik pede que se pare, se olhe, e se entenda por que chamam o Adriático de pérola.",
      "A cidade mais grandiosa da Croácia: a República de Ragusa (1358–1808) rivalizou com Veneza e foi notavelmente progressista — aboliu a escravidão em 1416 e teve serviço médico já em 1301.",
      "Suas muralhas são as mais bem preservadas do mundo; a rua de mármore Stradun e os telhados de terracota são hoje globalmente famosos como King's Landing, de Game of Thrones.",
    ],
    pointsOfInterest: [
      { name: "Gradske zidine (As Muralhas)", description: "~2 km sobre fortificações do séc. X, vistas de 360°. Ingresso ~€35; inclui as torres Minčeta e Bokar. Vá na abertura ou no fim da tarde.", coordinates: { lat: 42.6419, lng: 18.1069 } },
      { name: "Stradun (Placa)", description: "A avenida principal de calcário polido, do Portão Pile à Praça da Loggia — o eixo social da cidade.", coordinates: { lat: 42.6407, lng: 18.1106 } },
      { name: "Tvrđava Lovrijenac", description: "O “Gibraltar de Dubrovnik” sobre penhascos de 37 m; o Red Keep de Game of Thrones, com vista espetacular das muralhas.", coordinates: { lat: 42.6411, lng: 18.1052 } },
      { name: "Knežev dvor", description: "O Palácio do Reitor, gótico-renascentista — foi o palácio de Qarth em Game of Thrones." },
      { name: "Brdo Srđ (412 m)", description: "Teleférico ao melhor mirante — Cidade Velha, mar e ilhas. Espetacular ao pôr do sol. Alternativa grátis: Park Orsula.", coordinates: { lat: 42.6469, lng: 18.1108 } },
      { name: "Ilha de Lokrum", description: "Reserva natural a 15 min de barco, com pavões e o trono de ferro de GoT. Banho nas rochas e jardim botânico.", coordinates: { lat: 42.6256, lng: 18.1186 } },
    ],
    restaurantIds: ["restaurant-360", "nautika", "proto", "restaurant-dubrovnik", "banje-beach", "buza-bar"],
    gallery: [
      { src: "/images/dubrovnik-1.svg", alt: "Telhados de terracota da cidade velha" },
      { src: "/images/dubrovnik-2.svg", alt: "A Stradun ao entardecer" },
      { src: "/images/dubrovnik-3.svg", alt: "Vista do Monte Srđ sobre as muralhas" },
      { src: "/images/dubrovnik-4.svg", alt: "Bar Buža suspenso sobre as rochas" },
      { src: "/images/dubrovnik-5.svg", alt: "O porto antigo e o forte de São João" },
      { src: "/images/dubrovnik-6.svg", alt: "Ilha de Lokrum vista do mar" },
    ],
    practical: [
      { label: "Fundeio", value: "Porto de Gruž / baía de Dubrovnik" },
      { label: "Muralhas", value: "~€35 · entre na abertura, evite o calor" },
      { label: "Traje", value: "Sapato confortável para os degraus de pedra" },
      { label: "Sunset", value: "20:17 · Buža ou Monte Srđ" },
      { label: "Moeda", value: "Euro (€)" },
    ],
  },
  {
    slug: "peljesac",
    day: 5,
    date: "2026-07-29",
    name: "Pelješac",
    tagline: "Kučište · a península do vinho tinto e das ostras",
    route: "Dubrovnik → Kučište",
    coordinates: { lat: 42.9803, lng: 17.1247 },
    tempC: 29,
    sunset: "20:18",
    hero: { src: "/images/hero-peljesac.svg", alt: "Vinhedos íngremes de Dingač descendo até o mar" },
    introduction: [
      "Pelješac é a segunda maior península da Croácia: vinhedos íngremes, baías escondidas e ar perfumado de ervas e mar. Kučište é uma vila à beira-mar voltada para Korčula, vizinha de Viganj — paraíso de windsurf.",
      "Águas cristalinas e a proximidade de Korčula fazem da região um swim stop privilegiado — combinado com a lendária estrada do vinho e as ostras de Ston.",
    ],
    pointsOfInterest: [
      { name: "Estrada do vinho Dingač & Postup", description: "Encostas íngremes do melhor Plavac Mali da Croácia. Vinícolas Grgić, Korta Katarina, Saints Hills, Miloš e Matuško." },
      { name: "Ston & Mali Ston", description: "Muralhas de 5,5 km, salinas milenares e a ostra europeia nativa — piquenique de kamenice fresquíssimas com vinho de Pelješac." },
      { name: "Sveti Ilija (961 m)", description: "O pico do “Monte das Serpentes” — trilha desafiadora com vistas deslumbrantes do canal e de Korčula." },
      { name: "Žuljana · Divna · Prapratno", description: "Algumas das mais belas baías de Pelješac, em sua maioria de cascalho, com mar turquesa e fundeio tranquilo." },
      { name: "Viganj", description: "Vila vizinha de Kučište, referência mundial de windsurf graças ao vento maestral da tarde." },
      { name: "Naufrágio do Boka", description: "Ponto de mergulho perto de Mokalo: o naufrágio do navio Boka (anos 70)." },
    ],
    restaurantIds: [],
    gallery: [
      { src: "/images/peljesac-1.svg", alt: "Vinhedos de Dingač" },
      { src: "/images/peljesac-2.svg", alt: "Ostras de Mali Ston" },
      { src: "/images/hero-peljesac.svg", alt: "Encostas de Pelješac sobre o mar" },
      { src: "/images/peljesac-swim.svg", alt: "Enseada cristalina de Pelješac" },
    ],
    practical: [
      { label: "Não perca", value: "Dingač · ostras de Mali Ston" },
      { label: "Castas", value: "Plavac Mali · Dingač · Postup" },
      { label: "Leve", value: "Sapatilhas de água (cascalho, ouriços)" },
      { label: "Moeda", value: "Euro (€) · adegas só dinheiro" },
    ],
  },
  {
    slug: "makarska",
    day: 6,
    date: "2026-07-30",
    name: "Makarska",
    tagline: "Praias de cascalho sob a muralha do Biokovo",
    route: "Kučište → Makarska",
    coordinates: { lat: 43.2969, lng: 17.0178 },
    tempC: 30,
    sunset: "20:13",
    hero: { src: "/images/hero-makarska.svg", alt: "A riviera de Makarska sob a muralha do Biokovo" },
    introduction: [
      "O maior centro de veraneio da costa dálmata entre Split e Dubrovnik, numa baía em forma de ferradura entre o Adriático e o imponente maciço do Biokovo (a 2ª montanha mais alta da Croácia).",
      "Menos sobre sítios UNESCO e mais sobre o “verdadeiro verão”: cascalho cor de cobalto, promenade animada e a montanha como cenário de tirar o fôlego.",
    ],
    pointsOfInterest: [
      { name: "Biokovo & Skywalk", description: "Passarela de vidro suspensa a +1.200 m; cume Sveti Jure a 1.762 m. Estrada sinuosa, entrada limitada (20 carros/hora) — reserve horário." },
      { name: "Sveti Marko", description: "Igreja barroca de São Marcos, na praça central (Kačićev trg), com o maciço do Biokovo ao fundo." },
      { name: "Mosteiro Franciscano", description: "Séc. XV, que abriga um notável museu malacológico (de conchas)." },
      { name: "Park šuma Sveti Petar", description: "Parque florestal: península arborizada com trilha, farol, capela e enseadas para mergulho." },
      { name: "Spomenik turistu", description: "O “Monumento ao Turista”: escultura de bronze da gaivota Šime e uma turista, na orla — foto obrigatória." },
      { name: "Praias: Makarska · Nugal · Tučepi", description: "Cascalho branco urbano; Nugal (selvagem, ~30 min a pé/barco) e Tučepi (das mais longas da Riviera), sob pinheiros." },
    ],
    restaurantIds: ["jeny", "arta-larga", "riva-makarska", "jez", "the-above", "buba-beach"],
    gallery: [
      { src: "/images/makarska-1.svg", alt: "Praia sob o Biokovo" },
      { src: "/images/makarska-2.svg", alt: "Orla de Makarska" },
      { src: "/images/hero-makarska.svg", alt: "Riviera de Makarska" },
      { src: "/images/makarska-swim.svg", alt: "Águas da Riviera de Makarska" },
    ],
    practical: [
      { label: "Swim stop", value: "Ao pé do Biokovo" },
      { label: "Vista", value: "Skywalk Biokovo (reserve)" },
      { label: "Praias", value: "Nugal · Tučepi" },
      { label: "Moeda", value: "Euro (€)" },
    ],
  },
  {
    slug: "bol",
    day: 7,
    date: "2026-07-31",
    name: "Bol",
    tagline: "Zlatni Rat — o Chifre Dourado, praia-símbolo da Croácia",
    route: "Makarska → Bol",
    coordinates: { lat: 43.2606, lng: 16.6553 },
    tempC: 29,
    sunset: "20:15",
    hero: { src: "/images/hero-bol.svg", alt: "A língua de areia de Zlatni Rat avançando no mar" },
    introduction: [
      "Vila encantadora na costa sul da ilha de Brač, com um belo mosteiro dominicano quatrocentista. Mas sua fama mundial vem de Zlatni Rat (Chifre Dourado).",
      "É talvez a praia mais fotografada da Croácia — e a única da Europa que muda de forma e direção conforme o vento e as correntes, protegida por lei como monumento geomorfológico.",
    ],
    pointsOfInterest: [
      { name: "Zlatni Rat (Chifre Dourado)", description: "Promontório de ~500 m de seixos brancos finos que muda de forma com o maestral — a única praia da Europa que “se move”. Mar de clareza excepcional." },
      { name: "Vidova Gora (778 m)", description: "O pico mais alto de todas as ilhas do Adriático; a vista do promontório branco contra o mar azul, com Hvar ao sul, é inesquecível." },
      { name: "Mergulho & esportes", description: "Cavernas submarinas e paredões (centros Big Blue, Dolphin); windsurf e kitesurf de classe mundial no canal Brač–Hvar." },
      { name: "Mosteiro Dominicano", description: "Mosteiro quatrocentista na ponta leste, com vista do porto — o contraponto histórico ao cartão-postal da praia." },
      { name: "Vinícola Stina", description: "Na Riva de Bol, na 1ª Cooperativa da Dalmácia (1903); atraca à porta. Plavac Mali, Pošip e Vugava." },
      { name: "Vila de Bol", description: "Encantadora vila da costa sul de Brač, com orla de pedra branca e konobas à beira-mar." },
    ],
    restaurantIds: [],
    gallery: [
      { src: "/images/bol-1.svg", alt: "Zlatni Rat vista do alto" },
      { src: "/images/bol-2.svg", alt: "Águas de Brač" },
      { src: "/images/hero-bol.svg", alt: "O Chifre Dourado de Bol" },
      { src: "/images/bol-swim.svg", alt: "Águas cristalinas de Bol" },
    ],
    practical: [
      { label: "Praia", value: "Zlatni Rat" },
      { label: "Desembarque", value: "1 Ago · Marina Baotić, após o café" },
      { label: "Atenção", value: "Correntes na ponta — nade perto das margens" },
      { label: "Moeda", value: "Euro (€)" },
    ],
  },
];

export function getDestination(slug: string): Destination | undefined {
  return destinations.find((d) => d.slug === slug);
}

export const destinationSlugs = destinations.map((d) => d.slug);
