import Image from "next/image";
import { cn } from "@/lib/utils";
import photoMap from "@/lib/photo-map.json";

type PhotoEntry = { src: string; credit?: string; title?: string };
const PHOTOS = photoMap as Record<string, PhotoEntry>;

type Props = {
  src: string;
  alt: string;
  className?: string;
  /** Wrapper className for the relative positioning box. */
  wrapperClassName?: string;
  priority?: boolean;
  sizes?: string;
  /** Apply a slow ken-burns drift (for heroes). */
  kenBurns?: boolean;
};

/**
 * Full-bleed editorial image. Uses next/image with `fill`.
 *
 * If a real photo is registered for this slot (lib/photo-map.json, generated by
 * scripts/fetch-photos.mjs), it is used and optimised; otherwise the bespoke SVG
 * placeholder is served unoptimised. Swapping in official photos = edit the map.
 */
export function EditorialImage({
  src,
  alt,
  className,
  wrapperClassName,
  priority,
  sizes = "100vw",
  kenBurns,
}: Props) {
  const override = PHOTOS[src];
  const finalSrc = override?.src ?? src;
  const isSvg = finalSrc.toLowerCase().endsWith(".svg");
  return (
    <div className={cn("relative overflow-hidden", wrapperClassName)}>
      <Image
        src={finalSrc}
        alt={alt}
        fill
        sizes={sizes}
        priority={priority}
        unoptimized={isSvg}
        className={cn(
          "object-cover",
          kenBurns && "animate-ken-burns",
          className
        )}
      />
    </div>
  );
}
